/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import { IDL } from '@icp-sdk/core/candid';

const ConsultationResult = IDL.Record({
  flowType: IDL.Text,
  conditionScore: IDL.Nat,
  primaryConcern: IDL.Text,
  severity: IDL.Text,
  doshaImbalance: IDL.Text,
  rootCauses: IDL.Text,
  reportJson: IDL.Text,
  timestamp: IDL.Int,
});

export const idlService = IDL.Service({
  registerUser: IDL.Func([IDL.Text, IDL.Text], [], []),
  login: IDL.Func([IDL.Text, IDL.Text], [], ['query']),
  addAssessmentHistory: IDL.Func([IDL.Text], [], []),
  hasHistory: IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  saveConsultationResult: IDL.Func(
    [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
    [],
    []
  ),
  getConsultationResults: IDL.Func([IDL.Text], [IDL.Vec(ConsultationResult)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConsultationResult = IDL.Record({
    flowType: IDL.Text,
    conditionScore: IDL.Nat,
    primaryConcern: IDL.Text,
    severity: IDL.Text,
    doshaImbalance: IDL.Text,
    rootCauses: IDL.Text,
    reportJson: IDL.Text,
    timestamp: IDL.Int,
  });
  return IDL.Service({
    registerUser: IDL.Func([IDL.Text, IDL.Text], [], []),
    login: IDL.Func([IDL.Text, IDL.Text], [], ['query']),
    addAssessmentHistory: IDL.Func([IDL.Text], [], []),
    hasHistory: IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    saveConsultationResult: IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      []
    ),
    getConsultationResults: IDL.Func([IDL.Text], [IDL.Vec(ConsultationResult)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
