/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsultationResult {
  flowType: string;
  conditionScore: bigint;
  primaryConcern: string;
  severity: string;
  doshaImbalance: string;
  rootCauses: string;
  reportJson: string;
  timestamp: bigint;
}

export interface _SERVICE {
  registerUser: ActorMethod<[string, string], undefined>;
  login: ActorMethod<[string, string], undefined>;
  addAssessmentHistory: ActorMethod<[string], undefined>;
  hasHistory: ActorMethod<[string], boolean>;
  saveConsultationResult: ActorMethod<[string, string, bigint, string, string, string, string, string, bigint], undefined>;
  getConsultationResults: ActorMethod<[string], ConsultationResult[]>;
}

export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
