/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConsultationResult = IDL.Record({
  'conditionScore' : IDL.Nat,
  'flowType' : IDL.Text,
  'reportJson' : IDL.Text,
  'timestamp' : IDL.Int,
  'rootCauses' : IDL.Text,
  'doshaImbalance' : IDL.Text,
  'severity' : IDL.Text,
  'primaryConcern' : IDL.Text,
});
export const PasswordHash = IDL.Text;

export const idlService = IDL.Service({
  'addAssessmentHistory' : IDL.Func([IDL.Text], [], []),
  'getConsultationResults' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsultationResult)],
      ['query'],
    ),
  'hasHistory' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, PasswordHash], [], ['query']),
  'registerUser' : IDL.Func([IDL.Text, PasswordHash], [], []),
  'saveConsultationResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConsultationResult = IDL.Record({
    'conditionScore' : IDL.Nat,
    'flowType' : IDL.Text,
    'reportJson' : IDL.Text,
    'timestamp' : IDL.Int,
    'rootCauses' : IDL.Text,
    'doshaImbalance' : IDL.Text,
    'severity' : IDL.Text,
    'primaryConcern' : IDL.Text,
  });
  const PasswordHash = IDL.Text;
  
  return IDL.Service({
    'addAssessmentHistory' : IDL.Func([IDL.Text], [], []),
    'getConsultationResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsultationResult)],
        ['query'],
      ),
    'hasHistory' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, PasswordHash], [], ['query']),
    'registerUser' : IDL.Func([IDL.Text, PasswordHash], [], []),
    'saveConsultationResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };