/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PasswordHash = IDL.Text;

export const idlService = IDL.Service({
  'addAssessmentHistory' : IDL.Func([IDL.Text], [], []),
  'hasHistory' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, PasswordHash], [], ['query']),
  'registerUser' : IDL.Func([IDL.Text, PasswordHash], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PasswordHash = IDL.Text;
  
  return IDL.Service({
    'addAssessmentHistory' : IDL.Func([IDL.Text], [], []),
    'hasHistory' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, PasswordHash], [], ['query']),
    'registerUser' : IDL.Func([IDL.Text, PasswordHash], [], []),
  });
};

export const init = ({ IDL }) => { return []; };