/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsultationResult {
  'conditionScore' : bigint,
  'flowType' : string,
  'reportJson' : string,
  'timestamp' : bigint,
  'rootCauses' : string,
  'doshaImbalance' : string,
  'severity' : string,
  'primaryConcern' : string,
}
export type PasswordHash = string;
export interface _SERVICE {
  /**
   * / Record that a user has completed an assessment.
   */
  'addAssessmentHistory' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Return all consultation results for a user (most recent 20).
   */
  'getConsultationResults' : ActorMethod<[string], Array<ConsultationResult>>,
  /**
   * / Check whether a user has completed at least one assessment.
   * / Returns false (not an error) for unknown users so new-user flows work.
   */
  'hasHistory' : ActorMethod<[string], boolean>,
  /**
   * / Authenticate a user. Returns ok on success, err on failure.
   */
  'loginUser' : ActorMethod<
    [string, PasswordHash],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Register a new user with a hashed password.
   */
  'registerUser' : ActorMethod<
    [string, PasswordHash],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Persist a consultation result and mark the user as having history.
   */
  'saveConsultationResult' : ActorMethod<
    [string, string, bigint, string, string, string, string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];